name: CI

on:
  push:
    branches-ignore:
      - main
      - 'template-*'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ngocdanthanhtvu/hicommit-runner/.github/workflows/c-runner.yml@35880c4dd87f02f5b6ca1aef8ee2560094c9dd47
    with:
      api_base_url: https://hicommit.com/api
